version: '3'
services:
  node:
    image: ${REGISTRY}/${IMAGE_NAME}/${CI_COMMIT_REF_NAME}:${VERSION}
    command: run start:prod
    environment:
      NODE_ENV: production
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks: 
      - app-internal
    depends_on:
      - db
  
  db:
    image: mariadb:10.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/data
    networks: 
      - app-internal

networks: 
  app-internal:

volumes:
  db_data: